import { getInstallCommand } from "./install";
import type { CatalogItem } from "./types";

export const uiBrutalItems: CatalogItem[] = [
  {
    id: "accordion",
    name: "Accordion",
    kind: "component",
    variant: "ui-brutal",
    description: "Disclosure groups with animated base styling.",
    tags: ["disclosure", "content"],
    sourcePath: "src/registry/components/ui-brutal/accordion.tsx",
    previewPath: "src/catalog/previews/ui-brutal/accordion.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/accordion"),
  },
  {
    id: "alert",
    name: "Alert",
    kind: "component",
    variant: "ui-brutal",
    description: "Status messaging with icon and content slots.",
    tags: ["feedback", "status"],
    sourcePath: "src/registry/components/ui-brutal/alert.tsx",
    previewPath: "src/catalog/previews/ui-brutal/alert.tsx",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryUrl: "/r/brutal-alert.json",
    installCommand: getInstallCommand("brutal-alert"),
    loadPreview: () => import("@catalog/previews/ui-brutal/alert"),
  },
  {
    id: "badge",
    name: "Badge",
    kind: "component",
    variant: "ui-brutal",
    description: "Compact labels with semantic and generated hue variants.",
    tags: ["label", "status"],
    sourcePath: "src/registry/components/ui-brutal/badge.tsx",
    previewPath: "src/catalog/previews/ui-brutal/badge.tsx",
    dependencies: [
      "@base-ui/react",
      "class-variance-authority",
      "clsx",
      "tailwind-merge",
    ],
    registryUrl: "/r/brutal-badge.json",
    installCommand: getInstallCommand("brutal-badge"),
    loadPreview: () => import("@catalog/previews/ui-brutal/badge"),
  },
  {
    id: "button",
    name: "Button",
    kind: "component",
    variant: "ui-brutal",
    description: "Action primitive with variants, hues, and icon sizes.",
    tags: ["action", "form"],
    sourcePath: "src/registry/components/ui-brutal/button.tsx",
    previewPath: "src/catalog/previews/ui-brutal/button.tsx",
    dependencies: [
      "@base-ui/react",
      "class-variance-authority",
      "clsx",
      "tailwind-merge",
    ],
    registryUrl: "/r/brutal-button.json",
    installCommand: getInstallCommand("brutal-button"),
    loadPreview: () => import("@catalog/previews/ui-brutal/button"),
  },
  {
    id: "calendar",
    name: "Calendar",
    kind: "component",
    variant: "ui-brutal",
    description: "Date picker calendar styled for the brutal component set.",
    tags: ["date", "picker"],
    sourcePath: "src/registry/components/ui-brutal/calendar.tsx",
    previewPath: "src/catalog/previews/ui-brutal/calendar.tsx",
    dependencies: ["react-day-picker", "date-fns"],
    loadPreview: () => import("@catalog/previews/ui-brutal/calendar"),
  },
  {
    id: "card",
    name: "Card",
    kind: "component",
    variant: "ui-brutal",
    description: "Container primitives for grouped content.",
    tags: ["layout", "surface"],
    sourcePath: "src/registry/components/ui-brutal/card.tsx",
    previewPath: "src/catalog/previews/ui-brutal/card.tsx",
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryUrl: "/r/brutal-card.json",
    installCommand: getInstallCommand("brutal-card"),
    loadPreview: () => import("@catalog/previews/ui-brutal/card"),
  },
  {
    id: "hand-of-cards",
    name: "Hand Of Cards",
    kind: "component",
    variant: "ui-brutal",
    description: "Overlapping card fan layout for grouped surfaces.",
    tags: ["layout", "surface", "cards"],
    sourcePath: "src/registry/components/ui-brutal/hand-of-cards.tsx",
    previewPath: "src/catalog/previews/ui-brutal/hand-of-cards.tsx",
    dependencies: ["clsx", "tailwind-merge"],
    registryUrl: "/r/brutal-hand-of-cards.json",
    installCommand: getInstallCommand("brutal-hand-of-cards"),
    loadPreview: () => import("@catalog/previews/ui-brutal/hand-of-cards"),
  },
  {
    id: "chart",
    name: "Chart",
    kind: "component",
    variant: "ui-brutal",
    description: "Chart wrappers, tooltip content, and legend helpers.",
    tags: ["data", "visualization", "heavy"],
    sourcePath: "src/registry/components/ui-brutal/chart.tsx",
    previewPath: "src/catalog/previews/ui-brutal/chart.tsx",
    dependencies: ["recharts"],
    heavy: true,
    loadPreview: () => import("@catalog/previews/ui-brutal/chart"),
  },
  {
    id: "checkbox",
    name: "Checkbox",
    kind: "component",
    variant: "ui-brutal",
    description: "Checkbox control with checked and indeterminate states.",
    tags: ["form", "input"],
    sourcePath: "src/registry/components/ui-brutal/checkbox.tsx",
    previewPath: "src/catalog/previews/ui-brutal/checkbox.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/checkbox"),
  },
  {
    id: "command",
    name: "Command",
    kind: "component",
    variant: "ui-brutal",
    description: "Command palette composition built on cmdk.",
    tags: ["command", "search"],
    sourcePath: "src/registry/components/ui-brutal/command.tsx",
    previewPath: "src/catalog/previews/ui-brutal/command.tsx",
    dependencies: ["cmdk"],
    loadPreview: () => import("@catalog/previews/ui-brutal/command"),
  },
  {
    id: "context-menu",
    name: "Context Menu",
    kind: "component",
    variant: "ui-brutal",
    description: "Right-click menu primitives and submenu composition.",
    tags: ["menu", "overlay"],
    sourcePath: "src/registry/components/ui-brutal/context-menu.tsx",
    previewPath: "src/catalog/previews/ui-brutal/context-menu.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/context-menu"),
  },
  {
    id: "dialog",
    name: "Dialog",
    kind: "component",
    variant: "ui-brutal",
    description: "Modal dialog structure with header, footer, and close action.",
    tags: ["modal", "overlay"],
    sourcePath: "src/registry/components/ui-brutal/dialog.tsx",
    previewPath: "src/catalog/previews/ui-brutal/dialog.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/dialog"),
  },
  {
    id: "drawer",
    name: "Drawer",
    kind: "component",
    variant: "ui-brutal",
    description: "Drawer sheets powered by Vaul.",
    tags: ["drawer", "overlay"],
    sourcePath: "src/registry/components/ui-brutal/drawer.tsx",
    previewPath: "src/catalog/previews/ui-brutal/drawer.tsx",
    dependencies: ["vaul"],
    loadPreview: () => import("@catalog/previews/ui-brutal/drawer"),
  },
  {
    id: "dropdown-menu",
    name: "Dropdown Menu",
    kind: "component",
    variant: "ui-brutal",
    description: "Trigger-driven menu with grouped and nested actions.",
    tags: ["menu", "overlay"],
    sourcePath: "src/registry/components/ui-brutal/dropdown-menu.tsx",
    previewPath: "src/catalog/previews/ui-brutal/dropdown-menu.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/dropdown-menu"),
  },
  {
    id: "hover-card",
    name: "Hover Card",
    kind: "component",
    variant: "ui-brutal",
    description: "Hover-triggered contextual content.",
    tags: ["hover", "overlay"],
    sourcePath: "src/registry/components/ui-brutal/hover-card.tsx",
    previewPath: "src/catalog/previews/ui-brutal/hover-card.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/hover-card"),
  },
  {
    id: "input",
    name: "Input",
    kind: "component",
    variant: "ui-brutal",
    description: "Text input primitive with base form styling.",
    tags: ["form", "input"],
    sourcePath: "src/registry/components/ui-brutal/input.tsx",
    previewPath: "src/catalog/previews/ui-brutal/input.tsx",
    dependencies: [
      "@base-ui/react",
      "class-variance-authority",
      "clsx",
      "tailwind-merge",
    ],
    registryUrl: "/r/brutal-input.json",
    installCommand: getInstallCommand("brutal-input"),
    loadPreview: () => import("@catalog/previews/ui-brutal/input"),
  },
  {
    id: "input-otp",
    name: "Input OTP",
    kind: "component",
    variant: "ui-brutal",
    description: "One-time password input slots.",
    tags: ["form", "input", "otp"],
    sourcePath: "src/registry/components/ui-brutal/input-otp.tsx",
    previewPath: "src/catalog/previews/ui-brutal/input-otp.tsx",
    dependencies: ["input-otp"],
    loadPreview: () => import("@catalog/previews/ui-brutal/input-otp"),
  },
  {
    id: "popover",
    name: "Popover",
    kind: "component",
    variant: "ui-brutal",
    description: "Anchored floating content.",
    tags: ["overlay", "floating"],
    sourcePath: "src/registry/components/ui-brutal/popover.tsx",
    previewPath: "src/catalog/previews/ui-brutal/popover.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/popover"),
  },
  {
    id: "select",
    name: "Select",
    kind: "component",
    variant: "ui-brutal",
    description: "Single-value select with grouped items.",
    tags: ["form", "input", "menu"],
    sourcePath: "src/registry/components/ui-brutal/select.tsx",
    previewPath: "src/catalog/previews/ui-brutal/select.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/select"),
  },
  {
    id: "sheet",
    name: "Sheet",
    kind: "component",
    variant: "ui-brutal",
    description: "Side sheet overlay with directional variants.",
    tags: ["overlay", "panel"],
    sourcePath: "src/registry/components/ui-brutal/sheet.tsx",
    previewPath: "src/catalog/previews/ui-brutal/sheet.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/sheet"),
  },
  {
    id: "sonner",
    name: "Sonner",
    kind: "component",
    variant: "ui-brutal",
    description: "Sonner toast styling bridge.",
    tags: ["toast", "feedback"],
    sourcePath: "src/registry/components/ui-brutal/sonner.tsx",
    previewPath: "src/catalog/previews/ui-brutal/sonner.tsx",
    dependencies: ["sonner"],
    loadPreview: () => import("@catalog/previews/ui-brutal/sonner"),
  },
  {
    id: "toggle",
    name: "Toggle",
    kind: "component",
    variant: "ui-brutal",
    description: "Pressed-state button control.",
    tags: ["button", "state"],
    sourcePath: "src/registry/components/ui-brutal/toggle.tsx",
    previewPath: "src/catalog/previews/ui-brutal/toggle.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/toggle"),
  },
  {
    id: "tooltip",
    name: "Tooltip",
    kind: "component",
    variant: "ui-brutal",
    description: "Tooltip provider, trigger, and floating content.",
    tags: ["overlay", "hover"],
    sourcePath: "src/registry/components/ui-brutal/tooltip.tsx",
    previewPath: "src/catalog/previews/ui-brutal/tooltip.tsx",
    dependencies: ["@base-ui/react"],
    loadPreview: () => import("@catalog/previews/ui-brutal/tooltip"),
  },
];
